### ISSUE TITLE
Installing Boxwood causes a lot of errors and warnings (Linux)

### ISSUE THREAD

**Issue by zaiste** [buxlabs/boxwood#674]
Command:

```
npm i -g boxwood
```

Output:

```
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> sharp@0.26.2 install /home/zdun/.npm-packages/lib/node_modules/boxwood/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-linux-x64.tar.br
internal/fs/utils.js:269
    throw err;
    ^

Error: EACCES: permission denied, copyfile '/tmp/15664-libvips-8.10.0-linux-x64.tar.br' -> '/home/zdun/.npm/_libvips/libvips-8.10.0-linux-x64.tar.br'
    at Object.copyFileSync (fs.js:1907:3)
    at WriteStream.<anonymous> (/home/zdun/.npm-packages/lib/node_modules/boxwood/node_modules/sharp/install/libvips.js:121:16)
    at WriteStream.emit (events.js:314:20)
    at internal/fs/streams.js:247:14
    at FSReqCallback.oncomplete (fs.js:156:23) {
  errno: -13,
  syscall: 'copyfile',
  code: 'EACCES',
  path: '/tmp/15664-libvips-8.10.0-linux-x64.tar.br',
  dest: '/home/zdun/.npm/_libvips/libvips-8.10.0-linux-x64.tar.br'
}
make: Entering directory '/home/zdun/.npm-packages/lib/node_modules/boxwood/node_modules/sharp/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  AR(target) Release/obj.target/../node-addon-api/nothing.a
  COPY Release/nothing.a
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:24:10: fatal error: vips/vips8: No such file or directory
 #include <vips/vips8>
          ^~~~~~~~~~~~
compilation terminated.
sharp.target.mk:139: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/home/zdun/.npm-packages/lib/node_modules/boxwood/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.15.0-54-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/zdun/.npm-packages/lib/node_modules/boxwood/node_modules/sharp
gyp ERR! node -v v12.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> core-js@2.6.12 postinstall /home/zdun/.npm-packages/lib/node_modules/boxwood/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> esbuild@0.8.31 postinstall /home/zdun/.npm-packages/lib/node_modules/boxwood/node_modules/esbuild
> node install.js

npm WARN notsup Unsupported engine for boxwood@0.50.4: wanted: {"node":">= 14.15.1"} (current: {"node":"12.20.1","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: boxwood@0.50.4
npm WARN notsup Unsupported engine for abstract-syntax-tree@2.15.2: wanted: {"node":">=14.15.1"} (current: {"node":"12.20.1","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: abstract-syntax-tree@2.15.2
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sharp@0.26.2 (node_modules/boxwood/node_modules/sharp):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sharp@0.26.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

This is due some old dependencies e.g. `word-to-numbers`. 

Also, since Kretes depends on Boxwood those errors are also displayed when installing Kretes; tracking it in https://github.com/kreteshq/kretes/issues/114

**Comment by zaiste** [comment]
@emilos thanks for this quick fix! 

Also low priority: would it be also be possible to relax a bit `node` dependency from `14.x` to `12.x` ? or is there a specific reason for `14.x` ?

**Comment by emilos** [comment]
@zaiste yes, we can relax it. I just tried to follow the active LTS node.js schedule, but it's not a hard requirement.

**Comment by emilos** [comment]
@zaiste done :) `v0.51.1`
